# Generated by Django 5.2.11 on 2026-02-04 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinicial', models.DateTimeField()),
                ('tfinal', models.DateTimeField()),
                ('valor_ms', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('PREFERENCIAL', 'Preferencial')], max_length=15)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PRODUCAO', 'Producao'), ('FINALIZADO', 'Finalizado')], db_index=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'tipo', 'created_at'], name='core_pedido_status_761608_idx')],
            },
        ),
        migrations.CreateModel(
            name='FilaPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('usado_em_metrica', models.BooleanField(db_index=True, default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'indexes': [models.Index(fields=['finished_at', 'usado_em_metrica'], name='core_filapr_finishe_be5447_idx')],
            },
        ),
    ]
