# Generated by Django 5.2.11 on 2026-02-18 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("PREFERENCIAL", "Preferencial"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PRODUCAO", "Producao"),
                            ("FINALIZADO", "Finalizado"),
                            ("RETIRADO", "Retirado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "tipo", "created_at"],
                        name="core_pedido_status_761608_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Prato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("tempo_preparo_seg", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ativo"], name="core_prato_ativo_d471ad_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TMA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_tma_seg", models.FloatField()),
                ("calculado_em", models.DateTimeField(auto_now_add=True)),
                ("ultimo_prato_id", models.UUIDField(null=True)),
                (
                    "prato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.prato"
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrica TMA",
                "ordering": ["-calculado_em"],
            },
        ),
        migrations.CreateModel(
            name="FilaPrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preco_unitario", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_PRODUCAO", "Em Producao"),
                            ("FINALIZADO", "Finalizado"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("usado_em_metrica", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filas",
                        to="core.pedido",
                    ),
                ),
                (
                    "prato",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.prato",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prato", "status", "created_at"],
                        name="core_filapr_prato_i_84c208_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_filapr_status_ccf0f5_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="idx_fila_prioridade"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_filapr_created_872882_idx"
                    ),
                    models.Index(
                        fields=["usado_em_metrica", "status", "finished_at"],
                        name="core_filapr_usado_e_a05f12_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("finished_at__gte", models.F("started_at")),
                            ("finished_at__isnull", True),
                            _connector="OR",
                        ),
                        name="check_finished_after_started",
                    )
                ],
            },
        ),
    ]
