# Generated by Django 5.2.11 on 2026-02-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="filaprato",
            name="check_finished_after_started",
        ),
    ]
