# Generated by Django 5.2.11 on 2026-04-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_filaprato_check_finished_after_started"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prato",
            name="tempo_preparo_seg",
        ),
    ]
