# Generated by Django 5.2.11 on 2026-04-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_prato_tempo_preparo_seg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filaprato",
            name="prato",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="filas",
                to="core.prato",
            ),
        ),
    ]
