# Generated by Django 5.2.11 on 2026-04-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_filaprato_prato"),
    ]

    operations = [
        migrations.AddField(
            model_name="filaprato",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
